name: Development builds
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag andrew1013/carousel:dev
    - name: Publish Docker image
      run: |
        docker login -u andrew1013 -p ${{ secrets.DOCKER_TOKEN }}
        docker push andrew1013/carousel:dev